[package]
name = "mullvad-management-interface"
version = "0.1.0"
authors = ["Mullvad VPN"]
description = "Mullvad VPN IPC. Contains types and functions for IPC clients and servers."
license = "GPL-3.0"
edition = "2018"
publish = false

[dependencies]
err-derive = "0.2.1"
mullvad-paths = { path = "../mullvad-paths" }
tonic = "0.2"
tower = "0.3"
prost = "0.6"
prost-types = "0.6"
parity-tokio-ipc = "0.7"
futures = "0.3"
tokio = { version = "0.2", features =  [ "io-util", "process", "rt-core", "rt-threaded", "stream"] }
triggered = "0.1.1"
winapi = { version = "0.3", features = ["errhandlingapi", "handleapi", "libloaderapi", "ntlsa", "synchapi", "tlhelp32", "winbase", "winerror", "winuser"] }

[build-dependencies]
tonic-build = { version = "0.2", default-features = false, features = ["transport", "prost"] }
